### ISSUE TITLE
add "use_txrep" to sauserprefs_default_prefs

### ISSUE THREAD

**Issue by xpunkt** [johndoh/roundcube-sauserprefs#62]
i have installed roundcube-sauserprefs with succes, roundcube version 1.4.11, i just found that is miss use_txrep support, but i think this one is trikky since it cant be used in same time as awl, hope this can still be solved in someway

using postgresql as backend to save date

**Comment by johndoh** [comment]
Interesting. Because its an either/or type situation and I guess it will be server wide, admins will want their users either using one plugin or the other then may be the best idea is not to change the UI at all but instead add a config option for which config option (`use_auto_whitelist` or `use_txrep`) the auto whitelist tickbox uses.

**Comment by johndoh** [comment]
have a look at 6bfaba0 by adding `use_txrep` to the `sauserprefs_default_prefs` the plugin will use that over the `use_auto_whitelist` option.

**Comment by johndoh** [comment]
no feedback
